apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadowsocks-deployment
  labels:
    app: shadowsocks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shadowsocks
  template:
    metadata:
      labels:
        app: shadowsocks
    spec:
      containers:
      - name: shadowsocks-libev
        image: shadowsocks/shadowsocks-libev
        ports:
        - containerPort: 8388
        env:
        - name: METHOD
          value: ${method}
        - name: PASSWORD
          value: ${password}
---
apiVersion: v1
kind: Service
metadata:
  name: shadowsocks-svc
  labels:
    app: shadowsocks
spec:
  type: NodePort
  ports:
  - port: 8388
    protocol: TCP
  selector:
    app: shadowsocks
---
apiVersion: v1
kind: Service
metadata:
  name: shadowsocks-lb
  labels:
    app: shadowsocks
spec:
  selector:
    app: shadowsocks
  ports:
    - port: ${port}
      targetPort: 8388
  type: LoadBalancer
  